In [ ]:
from google.colab import files

uploaded = files.upload()

Saving Top Indian Places to Visit.csv to Top Indian Places to Visit.csv

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("Top Indian Places to Visit.csv")

In [ ]:
df.head()

,Unnamed: 0,Zone,State,City,Name,Type,Establishment Year,time needed to visit in hrs,Google review rating,Entrance Fee in INR,Airport with 50km Radius,Weekly Off,Significance,DSLR Allowed,Number of google review in lakhs,Best Time to visit
0,0,Northern,Delhi,Delhi,India Gate,War Memorial,1921,0.5,4.6,0,Yes,NaN,Historical,Yes,2.60,Evening
1,1,Northern,Delhi,Delhi,Humayun's Tomb,Tomb,1572,2.0,4.5,30,Yes,NaN,Historical,Yes,0.40,Afternoon
2,2,Northern,Delhi,Delhi,Akshardham Temple,Temple,2005,5.0,4.6,60,Yes,NaN,Religious,No,0.40,Afternoon
3,3,Northern,Delhi,Delhi,Waste to Wonder Park,Theme Park,2019,2.0,4.1,50,Yes,Monday,Environmental,Yes,0.27,Evening
4,4,Northern,Delhi,Delhi,Jantar Mantar,Observatory,1724,2.0,4.2,15,Yes,NaN,Scientific,Yes,0.31,Morning

In [ ]:
df.shape

(325, 16)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 325 entries, 0 to 324
Data columns (total 16 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Unnamed: 0                        325 non-null    int64
 1   Zone                              325 non-null    object
 2   State                             325 non-null    object
 3   City                              325 non-null    object
 4   Name                              325 non-null    object
 5   Type                              325 non-null    object
 6   Establishment Year                325 non-null    object
 7   time needed to visit in hrs       325 non-null    float64
 8   Google review rating              325 non-null    float64
 9   Entrance Fee in INR               325 non-null    int64
 10  Airport with 50km Radius          325 non-null    object
 11  Weekly Off                        32 non-null     object
 12  Significance                      325 non-null    object
 13  DSLR Allowed                      325 non-null    object
 14  Number of google review in lakhs  325 non-null    float64
 15  Best Time to visit                325 non-null    object
dtypes: float64(3), int64(2), object(11)
memory usage: 40.8+ KB

In [ ]:
df.describe()

,Unnamed: 0,time needed to visit in hrs,Google review rating,Entrance Fee in INR,Number of google review in lakhs
count,325.000000,325.000000,325.000000,325.000000,325.000000
mean,162.000000,1.807692,4.486154,115.809231,0.408438
std,93.963645,0.971398,0.274580,530.859785,0.646668
min,0.000000,0.500000,1.400000,0.000000,0.010000
25%,81.000000,1.000000,4.400000,0.000000,0.059000
50%,162.000000,1.500000,4.500000,0.000000,0.170000
75%,243.000000,2.000000,4.600000,40.000000,0.500000
max,324.000000,7.000000,4.900000,7500.000000,7.400000

In [ ]:
df.isnull().sum()

Unnamed: 0                            0
Zone                                  0
State                                 0
City                                  0
Name                                  0
Type                                  0
Establishment Year                    0
time needed to visit in hrs           0
Google review rating                  0
Entrance Fee in INR                   0
Airport with 50km Radius              0
Weekly Off                          293
Significance                          0
DSLR Allowed                          0
Number of google review in lakhs      0
Best Time to visit                    0
dtype: int64

In [ ]:
df.drop("Unnamed: 0", axis=1, inplace=True)

In [ ]:
df.columns

Index(['Zone', 'State', 'City', 'Name', 'Type', 'Establishment Year',
       'time needed to visit in hrs', 'Google review rating',
       'Entrance Fee in INR', 'Airport with 50km Radius', 'Weekly Off',
       'Significance', 'DSLR Allowed', 'Number of google review in lakhs',
       'Best Time to visit'],
      dtype='object')

In [ ]:
df["Weekly Off"] = df["Weekly Off"].fillna("Open All Days")

In [ ]:
df.isnull().sum()

Zone                                0
State                               0
City                                0
Name                                0
Type                                0
Establishment Year                  0
time needed to visit in hrs         0
Google review rating                0
Entrance Fee in INR                 0
Airport with 50km Radius            0
Weekly Off                          0
Significance                        0
DSLR Allowed                        0
Number of google review in lakhs    0
Best Time to visit                  0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df["Establishment Year"].unique()[:30]

array(['1921', '1572', '2005', '2019', '1724', '1700', '1986', '1648',
       '1400', '1600', '2003', '1500', '1954', '1959', '1192', '1992',
       'Unknown', '1924', '1922', '1996', '1881', '1831', '1431', '1987',
       '2013', '1878', '1760', '1870', '1956', '1997'], dtype=object)

In [ ]:
import numpy as np

df["Establishment Year"] = df["Establishment Year"].replace(
    "Unknown",
    np.nan
)

In [ ]:
df["Establishment Year"].isnull().sum()

np.int64(111)

In [ ]:
df["Establishment Year"].notnull().sum()

np.int64(214)

In [ ]:
df["Establishment Year"] = pd.to_numeric(
    df["Establishment Year"],
    errors="coerce"
)

In [ ]:
CURRENT_YEAR = 2026

df["Attraction Age"] = (
    CURRENT_YEAR - df["Establishment Year"]
)

In [ ]:
median_age = df["Attraction Age"].median()

df["Attraction Age"] = df["Attraction Age"].fillna(
    median_age
)

In [ ]:
df["Year Known"] = np.where(
    df["Establishment Year"].isnull(),
    "Unknown",
    "Known"
)

In [ ]:
def age_category(age):

    if age < 50:
        return "Modern"

    elif age < 200:
        return "Historic"

    elif age < 500:
        return "Heritage"

    else:
        return "Ancient"

In [ ]:
df["Age Category"] = df["Attraction Age"].apply(
    age_category
)

In [ ]:
df["Year Known"] = np.where(
    df["Establishment Year"].isnull(),
    "Unknown",
    "Known"
)

In [ ]:
df["Type"].value_counts()

Type
Temple                59
Beach                 25
Fort                  22
Lake                  16
National Park         14
                      ..
Rock Carvings          1
Entertainment          1
Commercial Complex     1
Mosque                 1
Race Track             1
Name: count, Length: 78, dtype: int64

In [ ]:
df["Best Time to visit"].value_counts()

Best Time to visit
All          164
Morning       88
Afternoon     44
Evening       26
All            1
Anytime        1
Night          1
Name: count, dtype: int64

In [ ]:
for x in df["Best Time to visit"].unique():
    print(repr(x))

'Evening'
'Afternoon'
'Morning'
'All'
'All '
'Anytime'
'Night'

In [ ]:
df["Best Time to visit"] = (
    df["Best Time to visit"]
    .str.strip()
)

In [ ]:
df["Best Time to visit"] = (
    df["Best Time to visit"]
    .replace("Anytime", "All")
)

In [ ]:
df["Best Time to visit"].value_counts()

Best Time to visit
All          166
Morning       88
Afternoon     44
Evening       26
Night          1
Name: count, dtype: int64

In [ ]:
df.head()

,Zone,State,City,Name,Type,Establishment Year,time needed to visit in hrs,Google review rating,Entrance Fee in INR,Airport with 50km Radius,Weekly Off,Significance,DSLR Allowed,Number of google review in lakhs,Best Time to visit,Attraction Age,Year Known,Age Category
0,Northern,Delhi,Delhi,India Gate,War Memorial,1921.0,0.5,4.6,0,Yes,Open All Days,Historical,Yes,2.60,Evening,105.0,Known,Historic
1,Northern,Delhi,Delhi,Humayun's Tomb,Tomb,1572.0,2.0,4.5,30,Yes,Open All Days,Historical,Yes,0.40,Afternoon,454.0,Known,Heritage
2,Northern,Delhi,Delhi,Akshardham Temple,Temple,2005.0,5.0,4.6,60,Yes,Open All Days,Religious,No,0.40,Afternoon,21.0,Known,Modern
3,Northern,Delhi,Delhi,Waste to Wonder Park,Theme Park,2019.0,2.0,4.1,50,Yes,Monday,Environmental,Yes,0.27,Evening,7.0,Known,Modern
4,Northern,Delhi,Delhi,Jantar Mantar,Observatory,1724.0,2.0,4.2,15,Yes,Open All Days,Scientific,Yes,0.31,Morning,302.0,Known,Heritage

In [ ]:
df.columns

Index(['Zone', 'State', 'City', 'Name', 'Type', 'Establishment Year',
       'time needed to visit in hrs', 'Google review rating',
       'Entrance Fee in INR', 'Airport with 50km Radius', 'Weekly Off',
       'Significance', 'DSLR Allowed', 'Number of google review in lakhs',
       'Best Time to visit', 'Attraction Age', 'Year Known', 'Age Category'],
      dtype='object')

In [ ]:
def budget_category(fee):

    if fee <= 50:
        return "Very Low"

    elif fee <= 200:
        return "Low"

    elif fee <= 500:
        return "Medium"

    else:
        return "High"

df["Budget Category"] = df["Entrance Fee in INR"].apply(
    budget_category
)

In [ ]:
df[["Entrance Fee in INR","Budget Category"]].head()

   Entrance Fee in INR Budget Category
0                    0        Very Low
1                   30        Very Low
2                   60             Low
3                   50        Very Low
4                   15        Very Low

In [ ]:
def duration_category(hours):

    if hours <= 2:
        return "Quick Visit"

    elif hours <= 4:
        return "Half Day"

    else:
        return "Full Day"

df["Duration Category"] = df[
    "time needed to visit in hrs"
].apply(duration_category)

In [ ]:
df[
    ["time needed to visit in hrs",
     "Duration Category"]
].head()

   time needed to visit in hrs Duration Category
0                          0.5       Quick Visit
1                          2.0       Quick Visit
2                          5.0          Full Day
3                          2.0       Quick Visit
4                          2.0       Quick Visit

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
scaler = MinMaxScaler()

In [ ]:
df["rating_scaled"] = scaler.fit_transform(
    df[["Google review rating"]]
)

In [ ]:
df["reviews_scaled"] = scaler.fit_transform(
    df[["Number of google review in lakhs"]]
)

In [ ]:
df["fee_scaled"] = scaler.fit_transform(
    df[["Entrance Fee in INR"]]
)

In [ ]:
df["Student Score"] = (
    0.5 * df["rating_scaled"]
    +
    0.3 * df["reviews_scaled"]
    +
    0.2 * (1 - df["fee_scaled"])
)

In [ ]:
df[
    ["Name","Student Score"]
].sort_values(
    by="Student Score",
    ascending=False
).head()

                                Name  Student Score
315      Buddh International Circuit       0.917143
17                  Gateway of India       0.802880
92   Golden Temple (Harmandir Sahib)       0.776725
306                        Kedarnath       0.766499
0                         India Gate       0.762285

In [ ]:
import numpy as np

df["Popularity Score"] = (
    df["Google review rating"]
    *
    np.log1p(
        df["Number of google review in lakhs"]
    )
)

In [ ]:
df["Tags"] = (
    df["Type"].astype(str)
    + " "
    + df["Significance"].astype(str)
    + " "
    + df["Budget Category"].astype(str)
    + " "
    + df["Duration Category"].astype(str)
    + " "
    + df["Best Time to visit"].astype(str)
)

In [ ]:
df[["Name","Tags"]].head()

                   Name                                               Tags
0            India Gate  War Memorial Historical Very Low Quick Visit E...
1        Humayun's Tomb     Tomb Historical Very Low Quick Visit Afternoon
2     Akshardham Temple            Temple Religious Low Full Day Afternoon
3  Waste to Wonder Park  Theme Park Environmental Very Low Quick Visit ...
4         Jantar Mantar  Observatory Scientific Very Low Quick Visit Mo...

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 325 entries, 0 to 324
Data columns (total 26 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Zone                              325 non-null    object
 1   State                             325 non-null    object
 2   City                              325 non-null    object
 3   Name                              325 non-null    object
 4   Type                              325 non-null    object
 5   Establishment Year                201 non-null    float64
 6   time needed to visit in hrs       325 non-null    float64
 7   Google review rating              325 non-null    float64
 8   Entrance Fee in INR               325 non-null    int64
 9   Airport with 50km Radius          325 non-null    object
 10  Weekly Off                        325 non-null    object
 11  Significance                      325 non-null    object
 12  DSLR Allowed                      325 non-null    object
 13  Number of google review in lakhs  325 non-null    float64
 14  Best Time to visit                325 non-null    object
 15  Attraction Age                    325 non-null    float64
 16  Year Known                        325 non-null    object
 17  Age Category                      325 non-null    object
 18  Budget Category                   325 non-null    object
 19  Duration Category                 325 non-null    object
 20  rating_scaled                     325 non-null    float64
 21  reviews_scaled                    325 non-null    float64
 22  fee_scaled                        325 non-null    float64
 23  Student Score                     325 non-null    float64
 24  Popularity Score                  325 non-null    float64
 25  Tags                              325 non-null    object
dtypes: float64(10), int64(1), object(15)
memory usage: 66.1+ KB

In [ ]:
df.to_csv(
    "processed_travel_dataset.csv",
    index=False
)

In [ ]:
from google.colab import files

files.download(
    "processed_travel_dataset.csv"
)