In [ ]:
import pandas as pd

df = pd.read_csv("processed_travel_dataset.csv")

In [ ]:
df.head()

,Zone,State,City,Name,Type,Establishment Year,time needed to visit in hrs,Google review rating,Entrance Fee in INR,Airport with 50km Radius,...,Year Known,Age Category,Budget Category,Duration Category,rating_scaled,reviews_scaled,fee_scaled,Student Score,Popularity Score,Tags
0,Northern,Delhi,Delhi,India Gate,War Memorial,1921.0,0.5,4.6,0,Yes,...,Known,Historic,Very Low,Quick Visit,0.914286,0.350474,0.000000,0.762285,5.892296,War Memorial Historical Very Low Quick Visit E...
1,Northern,Delhi,Delhi,Humayun's Tomb,Tomb,1572.0,2.0,4.5,30,Yes,...,Known,Heritage,Very Low,Quick Visit,0.885714,0.052774,0.004000,0.657889,1.514125,Tomb Historical Very Low Quick Visit Afternoon
2,Northern,Delhi,Delhi,Akshardham Temple,Temple,2005.0,5.0,4.6,60,Yes,...,Known,Modern,Low,Full Day,0.914286,0.052774,0.008000,0.671375,1.547772,Temple Religious Low Full Day Afternoon
3,Northern,Delhi,Delhi,Waste to Wonder Park,Theme Park,2019.0,2.0,4.1,50,Yes,...,Known,Modern,Very Low,Quick Visit,0.771429,0.035183,0.006667,0.594936,0.979969,Theme Park Environmental Very Low Quick Visit ...
4,Northern,Delhi,Delhi,Jantar Mantar,Observatory,1724.0,2.0,4.2,15,Yes,...,Known,Heritage,Very Low,Quick Visit,0.800000,0.040595,0.002000,0.611779,1.134114,Observatory Scientific Very Low Quick Visit Mo...

In [ ]:
def attractions_per_day(days):

    return days * 3

In [ ]:
attractions_per_day(2)

6

In [ ]:
def estimate_trip_cost(
    entrance_fee,
    days
):

    food_cost = days * 400

    transport_cost = days * 300

    total_cost = (
        entrance_fee
        +
        food_cost
        +
        transport_cost
    )

    return total_cost

In [ ]:
estimate_trip_cost(
    entrance_fee=500,
    days=2
)

1900

In [ ]:
def plan_trip(
    interest,
    budget,
    days
):

    num_places = attractions_per_day(days)

    matches = df[
        df["Tags"].str.contains(
            interest,
            case=False,
            na=False
        )
    ]

    matches = matches.sort_values(
        by="Student Score",
        ascending=False
    )

    selected_places = []

    total_fee = 0

    for _, row in matches.iterrows():

        fee = row["Entrance Fee in INR"]

        estimated_total = estimate_trip_cost(
            total_fee + fee,
            days
        )

        if estimated_total <= budget:

            selected_places.append(row)

            total_fee += fee

        if len(selected_places) >= num_places:

            break

    result = pd.DataFrame(
        selected_places
    )

    return result

In [ ]:
trip = plan_trip(
    interest="Historical",
    budget=5000,
    days=2
)

trip[
    [
        "Name",
        "City",
        "Entrance Fee in INR",
        "Student Score"
    ]
]

                 Name         City  Entrance Fee in INR  Student Score
17   Gateway of India       Mumbai                    0       0.802880
0          India Gate        Delhi                    0       0.762285
111     Mysore Palace       Mysore                   50       0.756892
181         Taj Mahal         Agra                   50       0.746743
86   Chittorgarh Fort  Chittorgarh                   40       0.732801
32          Charminar    Hyderabad                   25       0.727035

In [ ]:
total_entry_fee = trip[
    "Entrance Fee in INR"
].sum()

final_cost = estimate_trip_cost(
    total_entry_fee,
    days=2
)

print(final_cost)

1565

In [ ]:
budget = 5000

remaining = budget - final_cost

print(remaining)

3435

In [ ]:
print("Recommended Attractions")

display(
    trip[
        [
            "Name",
            "City",
            "Entrance Fee in INR"
        ]
    ]
)

print(
    f"Total Trip Cost: ₹{final_cost}"
)

print(
    f"Remaining Budget: ₹{remaining}"
)

Recommended Attractions

                 Name         City  Entrance Fee in INR
17   Gateway of India       Mumbai                    0
0          India Gate        Delhi                    0
111     Mysore Palace       Mysore                   50
181         Taj Mahal         Agra                   50
86   Chittorgarh Fort  Chittorgarh                   40
32          Charminar    Hyderabad                   25

Total Trip Cost: ₹1565
Remaining Budget: ₹3435

In [ ]:
def plan_trip(
    interest,
    budget,
    days,
    city=None
):

    num_places = attractions_per_day(days)

    matches = df[
        df["Tags"].str.contains(
            interest,
            case=False,
            na=False
        )
    ]

    if city:
        matches = matches[
            matches["City"].str.contains(
                city,
                case=False,
                na=False
            )
        ]

    matches = matches.sort_values(
        by="Student Score",
        ascending=False
    )

    selected_places = []

    total_fee = 0

    for _, row in matches.iterrows():

        fee = row["Entrance Fee in INR"]

        estimated_total = estimate_trip_cost(
            total_fee + fee,
            days
        )

        if estimated_total <= budget:

            selected_places.append(row)

            total_fee += fee

        if len(selected_places) >= num_places:
            break

    return pd.DataFrame(selected_places)

In [ ]:
trip = plan_trip(
    interest="Historical",
    budget=5000,
    days=2,
    city="Delhi"
)

trip[["Name", "City", "Entrance Fee in INR"]]

                 Name       City  Entrance Fee in INR
0          India Gate      Delhi                    0
7            Red Fort      Delhi                   35
14        Qutub Minar      Delhi                   35
313       Jama Masjid  New Delhi                    0
1      Humayun's Tomb      Delhi                   30
8    Agrasen ki Baoli      Delhi                    0

In [ ]:
def trip_summary(
    trip,
    budget,
    days
):

    total_entry_fee = trip[
        "Entrance Fee in INR"
    ].sum()

    total_cost = estimate_trip_cost(
        total_entry_fee,
        days
    )

    remaining_budget = (
        budget - total_cost
    )

    print("===== TRIP SUMMARY =====")

    print(
        f"Attractions Selected: {len(trip)}"
    )

    print(
        f"Entry Fees: ₹{total_entry_fee}"
    )

    print(
        f"Estimated Total Cost: ₹{total_cost}"
    )

    print(
        f"Remaining Budget: ₹{remaining_budget}"
    )

    return total_cost

In [ ]:
trip_summary(
    trip,
    budget=5000,
    days=2
)

===== TRIP SUMMARY =====
Attractions Selected: 6
Entry Fees: ₹100
Estimated Total Cost: ₹1500
Remaining Budget: ₹3500

np.int64(1500)

In [ ]:
attractions = trip[
    "Name"
].tolist()

print(attractions)

['India Gate', 'Red Fort', 'Qutub Minar', 'Jama Masjid', "Humayun's Tomb", 'Agrasen ki Baoli']